# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 20
  cycle_time_error_threshold: 0.5

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
      - Rev6
      - Slider8
      - Slider9
   sim_control_mode: 0 # 0: position, 1: velocity

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 20

gripper_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   # These joints can likely just be copied from the hardware_interface list above
   joints:
      - Slider8
      - Slider9

   constraints:
      goal_time: 10
      #stopped_position_tolerance: 0.4 # Defaults to 0.01
      Slider8:
          goal:       1
          trajectory: 1
      Slider9:
          goal:       1
          trajectory: 1

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   # These joints can likely just be copied from the hardware_interface list above
   joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
      - Rev6

   constraints:
      goal_time: 10
      #stopped_position_tolerance: 0.4 # Defaults to 0.01
      Rev1:
          goal:       1
          trajectory: 1
      Rev2:
          goal:       1
          trajectory: 1
      Rev3:
          goal:       1
          trajectory: 1
      Rev4:
          goal:       1
          trajectory: 1
      Rev5:
          goal:       1
          trajectory: 1
      Rev6:
          goal:       1
          trajectory: 1

   # gains:
   #     joint1: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint2: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}

    # state_publish_rate:  50 # Defaults to 50
    # action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

# Individual Position Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately
Rev1_position_controller:
   type: position_controllers/JointPositionController
   joint: Rev1
   pid: {p: 100.0, i: 0.01, d: 10.0}
Rev2_position_controller:
   type: position_controllers/JointPositionController
   joint: Rev2
   pid: {p: 100.0, i: 0.01, d: 10.0}
Rev3_position_controller:
   type: position_controllers/JointPositionController
   joint: Rev3
   pid: {p: 100.0, i: 0.01, d: 10.0}
Rev4_position_controller:
   type: position_controllers/JointPositionController
   joint: Rev4
   pid: {p: 100.0, i: 0.01, d: 10.0}
Rev5_position_controller:
   type: position_controllers/JointPositionController
   joint: Rev5
   pid: {p: 100.0, i: 0.01, d: 10.0}
Rev6_position_controller:
   type: position_controllers/JointPositionController
   joint: Rev6
   pid: {p: 100.0, i: 0.01, d: 10.0}
Slider8_position_controller:
   type: position_controllers/JointPositionController
   joint: Slider8
   pid: {p: 100.0, i: 0.01, d: 10.0}
Slider9_position_controller:
   type: position_controllers/JointPositionController
   joint: Slider9
   pid: {p: 100.0, i: 0.01, d: 10.0}

# Group Position Controllers ---------------------------------------
# Allows to send single ROS msg of Float64MultiArray to all joints
joint_position_controller:
   type: position_controllers/JointGroupPositionController
   joints:
     - Rev1
     - Rev2
     - Rev3
     - Rev4
     - Rev5
     - Rev6
