#!/usr/bin/python
import numpy as np
import cv2
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
import rospy
from std_msgs.msg import String
import rospkg

rospack = rospkg.RosPack()

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

fs = cv2.FileStorage(rospack.get_path('nsra_robot_vision') + "/storedPoints.yml", cv2.FILE_STORAGE_READ)

fn = fs.getNode("Points")

flag = False

x=fn.mat()[:,0,0]
y=fn.mat()[:,0,1]
z=fn.mat()[:,0,2]

ax.scatter(x, y, z)
plt.show()
